# 1. Write a Python program to compute and display the square root of a number entered by the user. (5)
import math

num = float(input('Enter a number: '))
num_sqrt = num ** 0.5

print('The square root of %0.3f is %0.3f' % (num, num_sqrt))

# or
import math

n = int(input("Enter a number: "))
print(math.sqrt(n))


# 2. Write a void function that takes a name, address, city, state, and zip as arguments and prints the arguments in
# the form of a mailing label (10):

def mailing_label(name, address, city, state, zip):
    print(name)
    print(address)
    print(city,",", state, zip)


name = input("Enter your name: ")
mailing_label(name)

address = input("Enter your address: ")
mailing_label(address)

city = input("Enter your city: ")
mailing_label(city)

state = input("Enter your state: ")
mailing_label(state)

zip = input("Enter your zip: ")
mailing_label(zip)

mailing_label(name, address, city, state, zip)


# 3. Write a function that takes two values and returns the maximum of the two values. (10)

def maximum(num1, num2):
    if num1 > num2:
        return num1
    else:
        return num2


x = 2
y = 3
print(max(x,y))

# 4. The date 6/10/60 is a "magic" date because the month times the day equals the year. Write a void function that
# takes a month, a day, and a year as arguments and displays a message saying the date is magic if the month times the
# day equals the year, and displays a message saying the date is not magic otherwise. (15)


def magic(month, day, year):
    if month*day == year:
        print("Magic date!")
    else:
        print("Not a magic date.")


magic(10,1,18)

# 5. Rewrite and improve the following program as a function that takes a numeric grade as an argument and returns the
# letter grade earned, assuming a 90-80-70...grading scale. (10)


def letter_grade():
    grade = int(input("Enter your numeric score: "))
    if grade >= 90:
        print("A")
    elif grade >= 80:
        print("B")
    elif grade >= 70:
        print("C")
    elif grade >= 60:
        print("D")
    else:
        print("F")


letter_grade()

# 6. The following short program generates a random number in the range 1-2:
# Write a void function that uses this program to simulate a coin toss. If the value generated by the call
# random.randint(1,2) is a 1, the function should display "heads".

import random

total_heads = 0
total_tails = 0
count = 0

while count < 1:

    coin = random.randint(1, 2)

    if coin == 1:
        print("Heads!\n")
        total_heads += 1
        count += 1

    elif coin == 2:
        print("Tails!\n")
        total_tails += 1
        count += 1

# or

import random


def coin_toss():
    x = random.randint(1,2)
    if x == 1:
        print("Heads")
    else:
        print("Tails")


x = 1
while x <= 10:
    coin_toss()
    x = x + 1